DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS transactionHistory;
DROP TABLE IF EXISTS status;



CREATE TABLE user
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  isAdmin BOOLEAN DEFAULT 0
);

CREATE TABLE status
(
  id INTEGER PRIMARY KEY,
  description TEXT NOT NULL
);

CREATE TABLE account
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  balance DECIMAL NOT NULL DEFAULT 10000,
  status_id INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  FOREIGN KEY (status_id) REFERENCES status (id)
);


CREATE TABLE product
(
  symbol TEXT PRIMARY KEY,
  name TEXT NOT NULL
);


CREATE TABLE transactionHistory
(
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  symbol TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  amount DECIMAL NOT NULL,
  price DECIMAL NOT NULL,
  t_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (symbol) REFERENCES product(symbol)
);